apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3403
        env:
        - name: BACKEND_URL
          value: "http://backend:3402"
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"