apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:\\app-data"  # Chemin Windows
  persistentVolumeReclaimPolicy: Retain